### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by fenderstr82** [JLindemann42/Atomic-Periodic-Table.Android#28]
Zoom not working

**Comment by fenderstr82** [comment]
in the playstore it works, not here

**Comment by JLindemann42** [comment]
Hello!

I have identified the issue and will soon start to work on a fix.

Thanks!

**Comment by JLindemann42** [comment]
Fixed in v.2.0.2-Build61

**Comment by fenderstr82** [comment]
It’s in Github?

**Comment by JLindemann42** [comment]
It's in the development branch and will be branched out to master and released this week.
