### ISSUE TITLE
Make Bottom toolbar permanently visible

### ISSUE THREAD

**Issue by electr1fy0** [JLindemann42/Atomic-Periodic-Table.Android#38]
**Is your feature request related to a problem? Please describe.**
When scrolling through the table, the bottom toolbar pops in and out way too often and is very distracting.

**Describe the solution you'd like**
Make it permanently visible or at least an option in Settings to do so.

**Comment by JLindemann42** [comment]
I have started work on this feature! Will be a settings option.

**Comment by JLindemann42** [comment]
Since 2.2.2 this is now available in the settings.
