### ISSUE TITLE
Issue with Installing the App on Android Version 13 Pixel Device from Play Store 

### ISSUE THREAD

**Issue by Ares-03** [JLindemann42/Atomic-Periodic-Table.Android#41]
![Screenshot_20240219-175805.png](https://github.com/JLindemann42/Atomic-Periodic-Table.Android/assets/106290878/2bb70db1-aade-4a16-a78b-0924f95d96dc)

Dear @JLindemann42

I hope this message finds you well. I wanted to bring to your attention an issue I encountered while attempting to install your app on my Pixel device running Android version 13.

Unfortunately, the app is not appearing for installation, presumably due to compatibility limitations with the newer Android version. I truly enjoy using your app and would greatly appreciate it if you could address this issue to ensure compatibility with Android 13.

While I understand that I can install the app directly from your GitHub repository, I believe it's crucial to highlight this problem to ensure a smoother experience for all users.

Thank you for your attention to this matter, and I look forward to seeing a resolution soon.

Best regards,
(Written with the help of AI)

**Comment by JLindemann42** [comment]
Hello!

I haven't been able to work on the app for a while, but will try to fix the comaptibility during the summer! Thanks for letting me know!

**Comment by Ares-03** [comment]
> Hello!
> 
> I haven't been able to work on the app for a while, but will try to fix the comaptibility during the summer! Thanks for letting me know!

Thanks for replying..

**Comment by JLindemann42** [comment]
Has been fixed!
