### ISSUE TITLE
When I click on an atom, app get crashes.

### ISSUE THREAD

**Issue by alr86** [JLindemann42/Atomic-Periodic-Table.Android#44]
**Describe the bug**
When I open the app and click on an atom, app get crashes.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9 [with Custom ROM]
 - OS: Android 14
 - Browser: native APK on izzyondroid
 - Version: 2.2.0

System crash log:

> https://paste.crdroid.net/PYUI98

**Comment by JLindemann42** [comment]
Thank you for the feedback! Will look into it as soon as possible!

**Comment by JLindemann42** [comment]
izzyondroid has uploaded a development build of the app where the issue was still a problem. Latest release that is available on the Play Store has it fixed, as well as the source code here. Will be uploaded to GitHub in the coming minutes.
