### ISSUE TITLE
App Crashes when tapping on an element.

### ISSUE THREAD

**Issue by derei** [JLindemann42/Atomic-Periodic-Table.Android#45]
**Describe the bug**
The app crashes when tapping on an element, or attempting to scroll the Tables page.

**To Reproduce**

Tap on any chemical element: -> instant crash.
Go to Tables, and attempt scrolling: -> instant crash.
Go to Tables and attempt to open Electrochemical Series: -> Page closes and the app is back to Mendeleev Table.
Tap on Isotopes: -> instant crash.
Go to Settings and tap on Report Issue: -> Instant crash.

**Expected behavior**
I'd expect the app to perform the intended actions, instead of crashing.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7Pro
 - OS: GrapheneOS ver. 2024070201
 - Browser: Vanadium

**Comment by JLindemann42** [comment]
Hello! Which version of the app are you using? Some development versions which has these issues have circled around on the internet.

**Comment by derei** [comment]
@JLindemann42 the one from IzzyOnDroid, 2.2.0.

**Comment by JLindemann42** [comment]
Download the latest APK here from GitHub or on the Play Store and it will work. The version on IzzyOnDroid is a development version of 2.2.0 that somehow have ended up there.
