### ISSUE TITLE
Group 1 elements get partially blocked when in landscape mode

### ISSUE THREAD

**Issue by FaqatZubair1** [JLindemann42/Atomic-Periodic-Table.Android#50]
**Describe the bug**
Whenever the app is in landscape mode, group 1 elements get partially blocked by period numbers

**Screenshots**

https://github.com/user-attachments/assets/98c8ee27-4340-4b48-bc9a-6e8eeebbde9e

**Smartphone (please complete the following information):**
 - Device: motorola 
 - OS: Android 14
 - Version 2.2.2

**Comment by JLindemann42** [comment]
Hello!

Thanks for letting me know and recently did some optimizations with the main table so might be caused by those. Will investigate when I have time!

Thanks,
Jonatan Lindemann

**Comment by JLindemann42** [comment]
I have just pushed v2.5.1 which has a fix for this issue! Thanks for letting me know!

**Comment by FaqatZubair1** [comment]
This version is not available on f-droid. Am I supposed to download it from github only, or are you planning to make it available on it soon?

**Comment by JLindemann42** [comment]
It should be available on F-Droid but otherwise download from the repo here at the moment!
